# Generated by Django 5.1.1 on 2025-01-09 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('prenume', models.CharField(max_length=50)),
                ('specializare', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Materie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=50)),
                ('materie', models.CharField(max_length=100)),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.profesor')),
            ],
        ),
    ]
