# Generated by Django 5.1.1 on 2025-01-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_profesor_materie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materie',
            name='materie',
        ),
        migrations.AddField(
            model_name='materie',
            name='durata_ore',
            field=models.IntegerField(default=2, max_length=3),
        ),
    ]
