# Generated by Django 5.1.1 on 2025-01-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_remove_materie_materie_materie_durata_ore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materie',
            name='durata_ore',
            field=models.IntegerField(default=5),
        ),
    ]
