# Generated by Django 5.1.1 on 2024-12-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LegoStore', '0002_customuser_cod_customuser_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cod',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
