# Generated by Django 5.1.1 on 2024-12-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LegoStore', '0003_alter_customuser_cod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='cod',
            new_name='code',
        ),
    ]
