# Generated by Django 5.1.1 on 2025-01-14 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LegoStore', '0007_customuser_blocked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('moderator-permissins', 'Moderator Permissions')]},
        ),
    ]
