# Generated by Django 5.1.1 on 2025-01-14 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LegoStore', '0008_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('moderator-permissions', 'Moderator Permissions')]},
        ),
    ]
